version: "3.9"

services:


# ===== Main Project =====
  main:
    image: ghcr.io/owner-name/${MAIN_PACKAGE_NAME}:latest
    container_name: ${MAIN}
    restart: unless-stopped
    ports:
      - "127.0.0.1:${MAIN_PORT}:80"
    networks:
      - docker-net

# ===== Cloudflare Tunnel (Token Method) =====
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ${CLOUDFLARED}
    restart: unless-stopped
    env_file:
      - .env
    command: tunnel run
    networks:
      - docker-net
    depends_on:
      - main



networks:
  docker-net:
    driver: bridge
    name: ${DOCKER_NET}
